"""add user type and projects

Revision ID: d4837b723eff
Revises: 76e93c2d2509
Create Date: 2025-04-10 15:33:33.918966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4837b723eff'
down_revision: Union[str, None] = '76e93c2d2509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SELLER', 'BUYER', name='usertype').create(op.get_bind())
    op.add_column('users', sa.Column('user_type', sa.Enum('SELLER', 'BUYER', name='usertype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
